version: '3.5'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./dbs-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER:     "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  app:
    image: docker.starground.co.uk/flask-sensor-api:latest
    depends_on:
      - "db"
    restart: always
    ports:
      - 8000:5000
    environment:
      DEBUG:          "${DEBUG}"
      FLASK_ENV:      "${FLASK_ENV}"
      APP_KEY:        "${APP_KEY}"
      FLASK_APP:      "${FLASK_APP}"
      MYSQL_HOST:     "${MYSQL_HOST}"
      MYSQL_DB:       "${MYSQL_DB}"
      MYSQL_USER:     "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

