---
 apiVersion: kustomize.config.k8s.io/v1beta1
 kind: Kustomization

 namespace: sensor-logger

 generatorOptions:
   disableNameSuffixHash: true

 secretGenerator:
 - name: ssl-cert
   namespace: sensor-logger
   files:
   - certs/tls.key
   - certs/tls.crt
   type: "kubernetes.io/tls"

 resources:
 - sl-ns.yaml
 - sl-dep.yaml
 - sl-svc.yaml
 - sl-ing.yaml
 - sl-config.yaml

...
