---
apiVersion: v1
kind: Service
metadata:
  name: sl-svc
  namespace: sensor-logger
  labels:
    app: sl-svc
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer
  selector:
    app: sl-dep
